// The two index files carry a generated <link rel="modulepreload"> list, and
// this is the only thing that writes it.
//
//   node tools/preload.mjs          rewrite both lists from the import graph
//   node tools/preload.mjs --check  exit 1 when either list is stale (lint runs this)
//
// Why it exists. The game is a folder of ES modules and the browser discovers
// them one level at a time: nothing in `main.js` runs until every module it
// names has arrived, and each of those has to arrive before *its* imports are
// even requested. At `/` that is four dependent round trips to the edge before
// the first line of the game runs (main.js, then 73 modules, then 67, then 35);
// at `/computer/` the workstation shell is imported *after* all of that and
// walks four more. Each round trip is one visit to the CDN edge, and a slow
// response early on holds everything behind it — which is where the
// occasional five-to-seven-second title came from. Listing the whole graph in
// the HTML lets the browser ask for all of it the moment the page lands.
// Measured on the deployed host, six interleaved runs each: the title at 2.0 s
// → 1.5 s median, and the worst run 6.6 s → 2.4 s.
//
// It is not a build step. The page works without the list, and a stale one is
// a slower first load rather than a broken page — which is exactly why it has
// to be checked by lint, because nothing else would ever notice.
//
// What is listed: every module statically reachable from the entry, in
// discovery order (breadth-first, alphabetical within a level), so the browser
// requests the earliest-needed files first. `/computer/` adds the workstation
// shell's graph, because that route always imports it. Dynamic imports are
// otherwise not followed: `src/dev.js` is `?dev=1` only.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Both index files reference the tree the same way — `src/main.js`, relative
// — and `computer/index.html` resolves it through its `<base href="/">`, so
// one href form serves both.
export const PAGES = [
  { file: 'index.html', entries: ['src/main.js'] },
  { file: 'computer/index.html', entries: ['src/main.js', 'src/ui/os/shell.js'] },
];

const BEGIN = '<!-- modulepreload:begin -->';
const END = '<!-- modulepreload:end -->';

// Static `import … from '…'`, `import '…'` and `export … from '…'` at the start
// of a line, comments stripped first. Dynamic `import()` is deliberately not
// matched. This is the same walk the load-time measurement used, and the
// browser fetched exactly the modules it found.
const STATIC = /(?:^|\n)\s*(?:import|export)\s[^'";]*?from\s*['"]([^'"]+)['"]|(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g;

function imports(file) {
  const src = fs.readFileSync(path.join(ROOT, file), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:'"\\])\/\/.*$/gm, '$1');
  const out = [];
  for (const m of src.matchAll(STATIC)) {
    const spec = m[1] || m[2];
    if (!spec || !spec.startsWith('.')) continue;
    out.push(path.posix.normalize(path.posix.join(path.posix.dirname(file), spec)));
  }
  return out.sort();
}

/** Every module statically reachable from `entry`, breadth-first. */
export function graph(entry) {
  const seen = new Set([entry]);
  const q = [entry];
  while (q.length) {
    const f = q.shift();
    if (!fs.existsSync(path.join(ROOT, f))) throw new Error(`${f} is imported but does not exist`);
    for (const t of imports(f)) if (!seen.has(t)) { seen.add(t); q.push(t); }
  }
  return [...seen];
}

/** The hrefs a page should preload, in request order, without duplicates. */
export function listFor(page) {
  const out = [];
  const seen = new Set();
  for (const e of page.entries) for (const f of graph(e)) if (!seen.has(f)) { seen.add(f); out.push(f); }
  return out;
}

function block(hrefs) {
  return [
    BEGIN,
    '<!-- Generated by `node tools/preload.mjs`; lint fails when this is stale.',
    '     Every module the page will load, so the browser fetches them all at',
    '     once instead of discovering them a level at a time. -->',
    ...hrefs.map((h) => `<link rel="modulepreload" href="${h}" />`),
    END,
  ].join('\n');
}

/** What the page currently lists, or null when it has no block. */
export function current(page) {
  const html = fs.readFileSync(path.join(ROOT, page.file), 'utf8');
  const a = html.indexOf(BEGIN), b = html.indexOf(END);
  if (a < 0 || b < 0) return null;
  return [...html.slice(a, b).matchAll(/href="([^"]+)"/g)].map((m) => m[1]);
}

/** One entry per stale page: `{ file, missing, extra }`. Empty means current. */
export function stale() {
  const out = [];
  for (const page of PAGES) {
    const want = listFor(page);
    const have = current(page);
    if (!have) { out.push({ file: page.file, missing: want.length, extra: 0, noBlock: true }); continue; }
    const w = new Set(want), h = new Set(have);
    const missing = want.filter((x) => !h.has(x)).length;
    const extra = have.filter((x) => !w.has(x)).length;
    const reordered = !missing && !extra && want.some((x, i) => have[i] !== x);
    if (missing || extra || reordered) out.push({ file: page.file, missing, extra, reordered });
  }
  return out;
}

export function write() {
  const report = [];
  for (const page of PAGES) {
    const file = path.join(ROOT, page.file);
    const html = fs.readFileSync(file, 'utf8');
    const a = html.indexOf(BEGIN), b = html.indexOf(END);
    if (a < 0 || b < 0) throw new Error(`${page.file}: no ${BEGIN} … ${END} markers to write between`);
    const hrefs = listFor(page);
    const next = html.slice(0, a) + block(hrefs) + html.slice(b + END.length);
    const changed = next !== html;
    if (changed) fs.writeFileSync(file, next);
    report.push({ file: page.file, count: hrefs.length, changed });
  }
  return report;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--check')) {
    const s = stale();
    for (const x of s) console.log(`  ✗ ${x.file}: modulepreload list is ${x.noBlock ? 'missing' : 'stale'}`
      + (x.noBlock ? '' : ` (${x.missing} module(s) not listed, ${x.extra} listed but not imported${x.reordered ? ', order changed' : ''})`)
      + ' — run node tools/preload.mjs');
    if (!s.length) console.log(`  preload lists current — ${PAGES.map((p) => `${p.file}: ${listFor(p).length}`).join(' · ')}`);
    process.exit(s.length ? 1 : 0);
  }
  for (const r of write()) console.log(`  ${r.changed ? 'wrote' : 'unchanged'} ${r.file}: ${r.count} modules`);
}
